# Generated by Django 4.2 on 2023-04-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_resetpasswordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordmodel',
            name='new_password',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
