# Generated by Django 4.2 on 2023-04-10 05:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='mock exam', max_length=125)),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MockExamWritingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mock/writing')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='MockExamReadingPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mock/reading')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='MockExamReadingAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='mock/reading')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='MockExamReadingAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mock/reading')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='MockExamListeningPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mock/listening')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='MockExamListeningAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='mock/listening')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
        migrations.CreateModel(
            name='MockExamListeningAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='mock/listening')),
                ('yuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mockexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel')),
            ],
        ),
    ]
