# Generated by Django 4.2 on 2023-04-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockexam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockExamReadingAudioModel',
        ),
    ]
