# Generated by Django 4.2 on 2023-04-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpaymentmodel',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
