# Generated by Django 4.2 on 2023-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_payment', '0002_alter_lessonpaymentmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpaymentmodel',
            name='cancel_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lessonpaymentmodel',
            name='perform_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
