# Generated by Django 4.2 on 2023-04-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_teachersmodel_info_teachersmodel_age_and_more'),
        ('lesson_payment', '0003_alter_lessonpaymentmodel_cancel_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonpaymentmodel',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lessonpaymentmodel',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.teachersmodel'),
            preserve_default=False,
        ),
    ]
