# Generated by Django 4.2 on 2023-04-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_payment', '0002_mockpaymentmodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpaymentmodel',
            name='isOver',
            field=models.BooleanField(default=False),
        ),
    ]
