# Generated by Django 4.2 on 2023-04-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mockexam', '0002_delete_mockexamreadingaudiomodel'),
        ('mock_payment', '0003_mockpaymentmodel_isover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockpaymentmodel',
            name='mockexam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockexam.mockexammodel'),
        ),
        migrations.AlterField(
            model_name='mockpaymentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
